<?php

/**
 * @file
 * Main module code
 */

/**
 * Implements hook_theme().
 */
function ppp_legacy_theme() {
  return [
    'ppp_post_sidebar' => [
      'variables' => ['user' => NULL],
    ],
    'ppp_post_body' => [
      'variables' => ['user' => NULL, 'post' => NULL, 'in_topic' => TRUE],
    ],
  ];
}

/**
 * Determine whether a user has access to a forum.
 */
function _ppp_legacy_access($forum) {
  $classified = in_array($forum, variable_get('ppp_legacy_classified_fora', []));
  if (!$classified) return TRUE;
  if (user_access('read classified content')) {
    drupal_set_message(t('Viewing classified content.'), 'error');
    return TRUE;
  }
  return FALSE;
}

function _ppp_legacy_access_user($uid) {
  $uids =& drupal_static(__FUNCTION__);
  if (!isset($uids)) {
    $uids = preg_split('/\s+/', variable_get('ppp_legacy_classified_users', ''));
  }

  if (!in_array($uid, $uids)) return TRUE;
  if (user_access('read classified content')) {
    drupal_set_message(t('Viewing classified content.'), 'error');
    return TRUE;
  }
  return FALSE;
}

function ppp_legacy_filter_info() {
  $filters['linebreaks'] = [
    'title' => t('Render linebreaks'),
    'description' => t('A filter that avoids the core shenanigans.'),
    'process callback' => '_ppp_legacy_filter_linebreaks',
  ];
  return $filters;
}

function _ppp_legacy_filter_linebreaks($text) {
  return str_replace("\n", '<br />', $text);
  // There. How hard was that?
}

function ppp_legacy_xbbcode_info() {
  $tags['quote'] = [
    'description' => t('UBB-style quote tag'),
    'callback' => '_ppp_legacy_xbbcode_quote',
    'sample' => '[quote]Originally written by Arancaytar:[b]He who quotes himself is a fool.[/b][/quote]',
  ];
  return $tags;
}

function _ppp_legacy_xbbcode_quote($tag) {
  $out = '<blockquote><span class="ppp-quote-label">quote:</span><hr />';
  if ($tag->option) {
    $out .= 'Originally written by ' . $tag->option . ':<br />';
  }
  $out .= $tag->content . '<hr /></blockquote>';
  return $out;
}
