<?php

/**
 * @file
 * Main module code
 */

/**
 * Implements hook_menu().
 */
function ppp_legacy_menu() {
  $menu['archives'] = [
    'title' => 'Archives',
    'page callback' => '_ppp_legacy_page_main',
    'file' => 'ppp_legacy.main.inc',
    'access arguments' => ['access content'],
  ];

  $menu['topic/%/%'] = [
    'title callback' => '_ppp_legacy_title_topic',
    'title arguments' => [1, 2],
    'page callback' => '_ppp_legacy_page_topic',
    'page arguments' => [1, 2],
    'access callback' => '_ppp_legacy_access',
    'access arguments' => [1],
    'file' => 'ppp_legacy.topic.inc',
    'type' => MENU_CALLBACK,
  ];

  $menu['forum/%'] = [
    'title callback' => '_ppp_legacy_title_forum',
    'title arguments' => [1],
    'page callback' => '_ppp_legacy_page_forum',
    'page arguments' => [1],
    'access callback' => '_ppp_legacy_access',
    'access arguments' => [1],
    'file' => 'ppp_legacy.forum.inc',
    'type' => MENU_CALLBACK,
  ];

  $menu['member/%'] = [
    'title callback' => '_ppp_legacy_title_user',
    'title arguments' => [1],
    'page callback' => '_ppp_legacy_page_user',
    'page arguments' => [1],
    'access callback' => '_ppp_legacy_access_user',
    'access arguments' => [1],
    'file' => 'ppp_legacy.user.inc',
    'type' => MENU_CALLBACK,
  ];

  $menu['admin/config/ppp'] = [
    'title' => 'PPP Archive',
    'description' => 'Settings related to the Pied Piper Project',
    'position' => 'right',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['_ppp_legacy_admin'],
    'access arguments' => ['administer site configuration'],
    'file' => 'ppp_legacy.admin.inc',
  ];

  return $menu;
}

/**
 * Implements hook_theme().
 */
function ppp_legacy_theme() {
  return [
    'ppp_post_sidebar' => [
      'template' => 'ppp_legacy_post_sidebar',
      'variables' => ['user' => NULL],
    ],
    'ppp_post_body' => [
      'template' => 'ppp_legacy_post_body',
      'variables' => ['user' => NULL, 'post' => NULL, 'in_topic' => TRUE],
    ],
  ];
}

/**
 * Determine whether a user has access to a forum.
 */
function _ppp_legacy_access($forum) {
  return (!in_array($forum, variable_get('ppp_legacy_classified_fora', [])) || user_access('read classified content'));
}

function _ppp_legacy_access_user($uid) {
  $uids =& drupal_static(__FUNCTION__);
  if (!isset($uids)) {
    $uids = explode("\n", variable_get('ppp_legacy_classified_users', ''));
  }
  return (!in_array($uid, $uids) || user_access('read classified content'));
}

function ppp_legacy_filter_info() {
  $filters['linebreaks'] = [
    'title' => t('Render linebreaks'),
    'description' => t('A filter that avoids the core shenanigans.'),
    'process callback' => '_ppp_legacy_filter_linebreaks',
  ];
  return $filters;
}

function _ppp_legacy_filter_linebreaks($text) {
  return str_replace("\n", '<br />', $text);
  // There. How hard was that?
}

function ppp_legacy_xbbcode_info() {
  $tags['quote'] = [
    'description' => t('UBB-style quote tag'),
    'callback' => '_ppp_legacy_xbbcode_quote',
    'sample' => '[quote]Originally written by Arancaytar:[b]He who quotes himself is a fool.[/b][/quote]',
  ];
  return $tags;
}

function _ppp_legacy_xbbcode_quote($tag) {
  $out = '<blockquote><span class="ppp-quote-label">quote:</span><hr />';
  if ($tag->option) {
    $out .= 'Originally written by ' . $tag->option . ':<br />';
  }
  $out .= $tag->content . '<hr /></blockquote>';
  return $out;
}
