ppp.settings:
  type: config_object
  label: 'PPP Settings'
  mapping:
    classified:
      type: mapping
      label: 'Classification settings'
      mapping:
        forum:
          label: 'Classified fora'
          type: sequence
          sequence:
            type: integer
            label: 'Forum ID'
        topic:
          type: sequence
          label: 'Classified topics'
          sequence:
            type: mapping
            label: 'Classified topic'
            mapping:
              forum:
                type: integer
                label: 'Forum ID'
              topic:
                type: integer
                label: 'Topic ID'
        user:
          type: sequence
          label: 'Classified members'
          sequence:
            type: integer
            label: 'Member ID'

ppp.forum_category.*:
  type: config_entity
  label: 'PPP Forum Category'
  mapping:
    cid:
      type: integer
      label: 'Category ID'
    name:
      type: string
      label: 'Name'

ppp.forum.*:
  type: config_entity
  label: 'PPP Forum'
  mapping:
    fid:
      type: integer
      label: 'Forum ID'
    name:
      type: string
      label: 'Name'
    description:
      type: string
      label: 'Description'
    category:
      type: integer
      label: 'Category'
    position:
      type: integer
      label: 'Weight'
